### ISSUE TITLE
Over encumbered triggers errors

### ISSUE THREAD

**Issue by NordikaMan** [ChuckTheSheep/zomboid-cnd-speech#24]
As soon as I started carrying too much I was suddenly spammed with this error 100's of times:

```
STACK TRACE
-----------------------------------------
function: generateSpeechFrom -- file: ConditionalSpeech__Core.lua line # 198
function: check_PlayerStatus -- file: ConditionalSpeech__Core.lua line # 324

ERROR: General     , 1620184465091> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: __concat not defined for operands: null and > at KahluaUtil.fail line:82.
ERROR: General     , 1620184465091> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: __concat not defined for operands: null and >
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:805)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:37)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:79)
	at zombie.characters.IsoPlayer.updateInternal2(IsoPlayer.java:1997)
	at zombie.characters.IsoPlayer.updateInternal1(IsoPlayer.java:1832)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.characters.IsoPlayer.update(IsoPlayer.java:1827)
	at zombie.MovingObjectUpdateSchedulerUpdateBucket.update(MovingObjectUpdateSchedulerUpdateBucket.java:69)
	at zombie.MovingObjectUpdateScheduler.update(MovingObjectUpdateScheduler.java:132)
	at zombie.iso.IsoCell.ProcessObjects(IsoCell.java:2890)
	at zombie.iso.IsoCell.updateInternal(IsoCell.java:5642)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoCell.update(IsoCell.java:5585)
	at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3176)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoWorld.update(IsoWorld.java:3102)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1593)
	at zombie.gameStates.IngameState.update(IngameState.java:1299)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:282)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:721)
	at zombie.GameWindow.run_ez(GameWindow.java:637)
	at zombie.GameWindow.mainThread(GameWindow.java:464)
	at java.lang.Thread.run(Thread.java:745)
LOG  : General     , 1620184465094> -----------------------------------------
```

**Comment by ChuckTheSheep** [comment]
Fixed with 33f32d6c7e57e2042892c4ffd1944dcee712ba7e
